In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
x= np.array([2,3,5,6,8,9,3,5,9])
print(x)
print('total element => ',x.size)
print('dimension wise elements =>' ,x.shape)
print('dimention count =>',x.ndim)


[2 3 5 6 8 9 3 5 9]
total element =>  9
dimension wise elements => (9,)
dimention count => 1


In [4]:
y= np.array([[2,3,5],[3,4,5]])
print(y)
print('total element => ',y.size)
print('dimension wise elements =>' ,y.shape)
print('dimention count =>',y.ndim)

[[2 3 5]
 [3 4 5]]
total element =>  6
dimension wise elements => (2, 3)
dimention count => 2


In [5]:
z= np.array([[2,3,5],[3,4,5],[1,2,3]])
print(z)
print('total element => ',z.size)
print('dimension wise elements =>' ,z.shape)
print('dimention count =>',z.ndim)

[[2 3 5]
 [3 4 5]
 [1 2 3]]
total element =>  9
dimension wise elements => (3, 3)
dimention count => 2


In [6]:
x=[1,3,5,7,9]
z=np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)
print('dimention count =>',z.ndim)
print('total element => ',z.size)

shape (3, 3, 5)
[[[1 3 5 7 9]
  [1 3 5 7 9]
  [1 3 5 7 9]]

 [[1 3 5 7 9]
  [1 3 5 7 9]
  [1 3 5 7 9]]

 [[1 3 5 7 9]
  [1 3 5 7 9]
  [1 3 5 7 9]]]
dimention count => 3
total element =>  45


In [7]:
x=[1,3,5,2,4,6,7,8,9,1]
z=np.array([x,x,x,x,x,x,x,x,x,x])
print('shape',z.shape)
print(z)
print('dimention count =>',z.ndim)
print('total element => ',z.size)

shape (10, 10)
[[1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]]
dimention count => 2
total element =>  100


In [8]:
d=np.arange(-10,11,.5)
d.shape


(42,)

In [9]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [10]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [11]:
a=np.linspace(1,1000,11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [41]:
d=np.random.randint(1,6,(10,10))
print(d)

[[4 2 3 1 4 5 2 4 3 2]
 [5 2 1 4 1 3 5 4 3 5]
 [3 2 3 3 1 1 2 5 1 5]
 [2 3 4 5 2 4 1 4 4 2]
 [2 3 1 4 2 2 1 5 2 4]
 [5 2 3 2 2 2 2 2 5 4]
 [3 5 3 1 1 2 4 3 1 3]
 [4 3 2 4 1 2 5 4 4 1]
 [3 5 3 1 4 5 3 4 1 1]
 [5 1 2 3 5 4 2 3 5 2]]


In [13]:
d[0]

array([5, 5, 4, 2, 1, 5, 1, 2, 4, 4])

In [14]:
d[0,0] #d[0][0]

5

In [15]:
d[3][5] #d[3,5]

4

In [16]:
d[:,0] #all rows of column idx 0

array([5, 3, 1, 5, 5, 3, 5, 5, 5, 4])

In [17]:
d[:5,2] # first five rows of column idx 2

array([4, 4, 4, 4, 5])

In [18]:
d[-1,5:] #last five item 

array([5, 2, 2, 2, 5])

In [19]:
d[:5,:5]

array([[5, 5, 4, 2, 1],
       [3, 4, 4, 2, 2],
       [1, 2, 4, 3, 5],
       [5, 2, 4, 2, 3],
       [5, 4, 5, 2, 1]])

In [20]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x,'\n',y)

[[7 7 5]
 [6 3 5]
 [1 8 9]] 
 [[5 7 8]
 [6 5 8]
 [1 2 4]]


In [21]:
x+y

array([[12, 14, 13],
       [12,  8, 13],
       [ 2, 10, 13]])

In [22]:
x-y

array([[ 2,  0, -3],
       [ 0, -2, -3],
       [ 0,  6,  5]])

In [23]:
x*y

array([[35, 49, 40],
       [36, 15, 40],
       [ 1, 16, 36]])

In [24]:
x/y

array([[1.4  , 1.   , 0.625],
       [1.   , 0.6  , 0.625],
       [1.   , 4.   , 2.25 ]])

In [25]:
x+10

array([[17, 17, 15],
       [16, 13, 15],
       [11, 18, 19]])

In [26]:
x*10

array([[70, 70, 50],
       [60, 30, 50],
       [10, 80, 90]])

In [27]:
x -10

array([[-3, -3, -5],
       [-4, -7, -5],
       [-9, -2, -1]])

In [28]:
np.dot(x,y)

array([[ 82,  94, 132],
       [ 53,  67,  92],
       [ 62,  65, 108]])

In [29]:
np.matmul(x,y)

array([[ 82,  94, 132],
       [ 53,  67,  92],
       [ 62,  65, 108]])

In [30]:
np.multiply(x,y)

array([[35, 49, 40],
       [36, 15, 40],
       [ 1, 16, 36]])

In [31]:
np.cross(x,y)

array([[ 21, -31,  14],
       [ -1, -18,  12],
       [ 14,   5,  -6]])

In [32]:
np.hstack([x,y])

array([[7, 7, 5, 5, 7, 8],
       [6, 3, 5, 6, 5, 8],
       [1, 8, 9, 1, 2, 4]])

In [33]:
np.vstack([x,y])

array([[7, 7, 5],
       [6, 3, 5],
       [1, 8, 9],
       [5, 7, 8],
       [6, 5, 8],
       [1, 2, 4]])

In [34]:
np.append(x,y,axis=0)

array([[7, 7, 5],
       [6, 3, 5],
       [1, 8, 9],
       [5, 7, 8],
       [6, 5, 8],
       [1, 2, 4]])

In [35]:
x.max()

9

In [36]:
x.max(axis=0)

array([7, 8, 9])

In [37]:
x.min(axis=1)

array([5, 3, 1])

In [38]:
x.flatten()

array([7, 7, 5, 6, 3, 5, 1, 8, 9])

In [39]:
d[d>3]#boolean filter

array([5, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 5, 5, 4, 4, 5, 5, 4, 5,
       4, 5, 4, 5, 4, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5, 4, 4, 4, 4, 4, 5, 5])

In [40]:
d[d==1] #give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])